# name: Black-formatter

# on: [push, pull_request]

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Run Black formatter (Apply changes)
#         uses: psf/black@stable
#         with:
#           args: "."  # Eliminamos "--check" para aplicar cambios automáticamente

#       - name: Run Black formatter (Check only)
#         uses: psf/black@stable
#         with:
#           args: "--check ."  # Agregamos "--check" para verificar sin cambios

name: Black formatter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Running and analysing the code with Black.
      run: |
        black .
        black --check .
